source: app
destination: app/_site

# Site settings
title: Geeked Out Solutions
subtitle: A blog about datacenter automation, chatbots, AI and more.
description: > # this means to ignore newlines until "baseurl:"
  A blog about datacenter automation, chatbots, AI and other geeky related things.

author: Brian Hopkins
author_website: https://www.geekedoutsolutions.com
email: geekedoutsolutions@gmail.com

baseurl: "/"  # Subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
                            # Currently `gulp serve:dist` does not work with a baseurl specified. For this purpose,
                            # temporarily comment out this parameter
url: "https://www.geekedoutsolutions.com"  # Base hostname & protocol for your site

twitter_username: ''
github_username:  geeked-out-solutions
disqus_shortname: geeked-out-solutions
google_analytics: UA-102614039-1

# Pagination
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Archive settings
jekyll-archives:
  enabled: ['tags']
